version: 0.2

phases:
  pre_build:
    commands:
      - $(aws ecr get-login --region us-east-1 --no-include-email)
      - REPOSITORY_URI=026191746148.dkr.ecr.us-east-1.amazonaws.com/first-app
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t first-app .
      - docker tag first-app $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
